name: Post message to WxT

on: push

jobs:
  wxt:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to WxT
        uses: qsnyder/action-wxt@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ROOMID: ${{ secrets.ROOMID }}
          MESSAGE: "Action completed successfully, triggered by commit SHA ${{ GITHUB_SHA }}"
